#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Update the bundled English Java coding guidelines markdown from the official
Alibaba GitHub repository (GitBook source, no PDF involved).

Pipeline:
  1. Download the README.md of alibaba/Alibaba-Java-Coding-Guidelines (the
     repository root README IS the full English manual in Markdown).
  2. Clean HTML remnants (<font ...> coloring, HTML entities, escaped rule
     numbers, split blockquote lines) and rebuild a tidy Markdown document.

Usage:
    python3 update_guidelines_en.py                    # download + regenerate default output
    python3 update_guidelines_en.py --local path.md    # use a local copy of the upstream README
    python3 update_guidelines_en.py --out /tmp/out.md  # custom output path

Requirements: Python >= 3.9, standard library only (no third-party deps).

Notes:
    - The generated Markdown is the authoritative copy checked into this repo
      at references/java-coding-guidelines-en.md. Do not hand-edit it; regenerate.
    - Upstream license: Apache-2.0 (alibaba/Alibaba-Java-Coding-Guidelines).
"""

import argparse
import html
import os
import re
import sys
import urllib.request

README_URL = (
    "https://raw.githubusercontent.com/alibaba/"
    "Alibaba-Java-Coding-Guidelines/master/README.md"
)
DEFAULT_OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "references",
    "java-coding-guidelines-en.md",
)

HEADER = """# Alibaba Java Coding Guidelines (English Edition)

> **Source**: the official English edition hosted at
> `alibaba/Alibaba-Java-Coding-Guidelines` (GitBook source; the repository root
> `README.md` is the full manual in Markdown). This file is a cleaned
> transcription of that Markdown.
> **License**: Apache-2.0 (same as the upstream Alibaba repositories).
> **Version note**: the English edition corresponds to an early version of the
> Chinese manual (approx. 1.0.x, 5 sections, 181 rules: 124 Mandatory /
> 57 Recommended / 24 For Reference). It predates the Huangshan v1.7.1 manual
> (7 sections, 327 rules). For the up-to-date Chinese manual, see
> `alibaba/p3c` or the companion skill `alibaba-java-coding-guidelines`.
> **Maintenance**: this file is generated by `scripts/update_guidelines_en.py`
> from the upstream README; do not hand-edit it. Run the script to update.

"""


def fetch_readme() -> str:
    """Download the upstream README, bypassing local HTTP proxies."""
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    opener.addheaders = [("User-Agent", "Mozilla/5.0")]
    with opener.open(README_URL, timeout=60) as resp:
        return resp.read().decode("utf-8")


def clean_inline(t: str) -> str:
    t = re.sub(r"</?font[^>]*>", "", t)
    t = html.unescape(t)
    t = t.replace("&dollar;", "$")
    return t


def clean_manual(src: str) -> str:
    lines = src.split("\n")
    out = []
    in_toc = False
    i = 0
    n = len(lines)

    def flush_quote(buf):
        res = []
        for kind, text in buf:
            prefix = {
                "pos": "**Positive example:** ",
                "neg": "**Counter example:** ",
                "note": "**Note:** ",
            }.get(kind, "")
            res.append("> " + prefix + text.strip())
        return res

    while i < n:
        s = lines[i].strip()

        if s.startswith("## Table of Contents"):
            in_toc = True
            i += 1
            continue
        if in_toc:
            if s.startswith("## Preface"):
                in_toc = False
            else:
                i += 1
                continue

        m = re.match(r"^(#{2,3})\s*(.*)$", s)
        if m:
            title = re.sub(r"</?font[^>]*>", "", m.group(2)).strip()
            out += ["", "#" * len(m.group(1)) + " " + title, ""]
            i += 1
            continue

        if s.startswith(">"):
            buf = []
            while i < n and lines[i].strip().startswith(">"):
                q = clean_inline(lines[i].strip()[1:].strip())
                if re.match(r"^(\*\*)?Positive example:(\*\*)?", q):
                    kind = "pos"
                    q = re.sub(r"^(\*\*)?Positive example:(\*\*)?\s*", "", q)
                elif re.match(r"^(\*\*)?Counter example:(\*\*)?", q):
                    kind = "neg"
                    q = re.sub(r"^(\*\*)?Counter example:(\*\*)?\s*", "", q)
                elif re.match(r"^(\*\*)?Note:(\*\*)?", q):
                    kind = "note"
                    q = re.sub(r"^(\*\*)?Note:(\*\*)?\s*", "", q)
                else:
                    kind = "plain"
                buf.append((kind, q))
                i += 1
            # attach continuation lines (multi-line examples without '>')
            while i < n:
                nx = lines[i].strip()
                if (
                    nx == ""
                    or nx.startswith((">", "#", "- ", "* "))
                    or re.match(r"^\d+[\.\)]", nx)
                ):
                    break
                cq = clean_inline(nx)
                if buf:
                    last_kind, last_text = buf[-1]
                    buf[-1] = (last_kind, last_text + " " + cq if last_text else cq)
                i += 1
            out.extend(flush_quote(buf))
            out.append("")
            continue

        t = clean_inline(s)
        t = re.sub(r"(\d+)\\\.", r"\1.", t)
        t = re.sub(r"[ \t]{2,}", " ", t)
        out.append("" if t == "" else t)
        i += 1

    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def stats(text: str) -> dict:
    return {
        "mandatory": text.count("**[Mandatory]**"),
        "recommended": text.count("**[Recommended]**"),
        "reference": text.count("**[For Reference]**"),
        "lines": text.count("\n"),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--local", help="use a local copy of the upstream README instead of downloading")
    ap.add_argument("--out", default=DEFAULT_OUT, help="output markdown path")
    args = ap.parse_args()

    if args.local:
        with open(args.local, encoding="utf-8") as f:
            src = f.read()
        print(f"Read local README: {args.local}")
    else:
        print(f"Downloading {README_URL} ...")
        src = fetch_readme()
        print(f"Downloaded {len(src)} bytes")

    body = clean_manual(src)
    # Prepend the metadata header and keep the full body (Preface + chapters 1-5).
    body = HEADER + body + "\n"

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(body)

    st = stats(body)
    print(f"Written: {args.out}")
    print(f"  lines={st['lines']}  mandatory={st['mandatory']}  "
          f"recommended={st['recommended']}  reference={st['reference']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
